# Generated by Django 6.1.1 on 2026-09-17 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo para novas reservas')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código do veículo')),
                ('categoria', models.CharField(choices=[('LEVE', 'Veículo leve'), ('COLETIVO', 'Veículo coletivo')], max_length=10, verbose_name='Categoria')),
                ('capacidade', models.PositiveSmallIntegerField(editable=False, verbose_name='Capacidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo para novas reservas')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('capacidade', 4), ('categoria', 'LEVE')), models.Q(('capacidade', 18), ('categoria', 'COLETIVO')), _connector='OR'), name='veiculo_categoria_capacidade_coerentes')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('solicitante', models.CharField(max_length=150, verbose_name='Solicitante')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('atividade', models.CharField(max_length=200, verbose_name='Atividade')),
                ('origem', models.CharField(max_length=150, verbose_name='Origem')),
                ('destino', models.CharField(max_length=150, verbose_name='Destino')),
                ('data', models.DateField(verbose_name='Data da reserva')),
                ('horario_saida', models.TimeField(verbose_name='Horário de saída')),
                ('horario_retorno', models.TimeField(verbose_name='Horário de retorno')),
                ('quantidade_passageiros', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Quantidade de passageiros')),
                ('categoria_pretendida', models.CharField(blank=True, choices=[('LEVE', 'Veículo leve'), ('COLETIVO', 'Veículo coletivo')], max_length=10, verbose_name='Categoria pretendida')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['data', 'horario_saida', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_passageiros__gte', 1), ('quantidade_passageiros__lte', 18)), name='reserva_passageiros_1_a_18'), models.CheckConstraint(condition=models.Q(('horario_retorno__gt', models.F('horario_saida'))), name='reserva_retorno_apos_saida')],
            },
        ),
    ]
